#!/usr/bin/python -tt
#
# Copyright 2009-2014 Eucalyptus Systems, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
# Please contact Eucalyptus Systems, Inc., 6755 Hollister Ave., Goleta
# CA 93117, USA or visit http://www.eucalyptus.com/licenses/ if you need
# additional information or have any questions.

import os
import sys
import getopt
import eucaimgworker
import eucaimgworker.config as config
from eucaimgworker.config import set_pidfile, set_boto_config
from eucaimgworker.logutil import CustomLog, set_loglevel, set_boto_loglevel, set_log_file_count, set_log_file_size
from eucaimgworker.main_loop import start_worker
from eucaimgworker import LOGGER_NAME


logger = CustomLog(LOGGER_NAME)

def daemonize(func=None):
    # Fork process
    procid = os.fork()
    if procid < 0:
        sys.exit(1)
    elif procid > 0:
        sys.exit(0)
    procid = os.setsid()
    if procid == -1:
        sys.exit(1)

    # Close open file descriptors
    for fd in (0, 1, 2):
        try:
            os.close(fd)
        except OSError:
            pass

    # Point descriptors to /dev/null
    os.open("/dev/null", os.O_RDWR)
    os.dup(0)
    os.dup(0)

    os.umask(027)
    os.chdir("/")

    # Import here since these are only necessary if we daemonize
    import fcntl
    import signal
    import atexit

    # Create pidfile
    try:
        f = open(config.pidfile, "w")
        fcntl.lockf(f, fcntl.LOCK_EX | fcntl.LOCK_NB)
        f.write(str(os.getpid()))
        f.flush()
    except IOError:
        logger.error("Failed to write pidfile %s", config.pidfile)
        sys.exit(1)

    signal.signal(signal.SIGTERM, cleanpid)
    atexit.register(cleanpid)

    if func:
        logger.info("Starting daemonized imaging worker process")
        func()


def cleanpid(signum=None, action=None):
    os.remove(config.pidfile)
    sys.exit(0)


def usage():
    print """
    %s [-d | --daemonize] [-p | --pidfile] [-l | --log-level]  [-b | --boto-log-level] [-c | --boto-config]
    """ % (os.path.basename(sys.argv[0]))
    sys.exit(1)


if __name__ == "__main__":
    daemon = False
    try:
        longopts = [
            "--help",
            "--daemonize",
            "--pidfile",
            "--log-level",
            "--boto-config",
        ]
        opts, _ = getopt.getopt(sys.argv[1:], "hdp:l:b:c:s:f:", longopts)
        for arg, value in opts:
            if arg == "-d" or arg == "--daemonize":
                daemon = True
            elif arg == "-p" or arg == "--pidfile":
                set_pidfile(value)
            elif arg == "-l" or arg == "--log-level":
                set_loglevel(value)
            elif arg == "-b" or arg == "--boto-log-level":
                set_boto_loglevel(value)
            elif arg == "-c" or arg == "--boto-config":
                set_boto_config(value)
            elif arg == "-f":
                set_log_file_count(value)
            elif arg == "-s":
                set_log_file_size(value)
            elif arg == "-h" or arg == "--help":
                usage()
    except getopt.GetoptError:
        usage()

    if daemon:
        daemonize(start_worker)
    else:
        try:
            logger.info("Starting Imaging Service")
            start_worker()
        except KeyboardInterrupt:
            logger.info("Interrupted By User")
            sys.exit(0)
